### PR TITLE
added colorized output for build (very useful for test output)

### PR DESCRIPTION
**Pull request by ekalosak**

### CODE REVIEW

**Comment by silverjam** [comment]
@mfine ?

**Comment by silverjam** [comment]
@mfine why not merge?

**Comment by mfine** [comment]
Because the default is intended to be minimal and not anticipate too many different desires. If you want fancier shake options, you can setup up your own `shakeMain'`.

**Comment by silverjam** [comment]
ok, that's what's currently done in SITL

**Pull request closed without merging**
